supported_roms = {
  sfiii3nr1 = {
    name = "Street Fighter III 3rd Strike (Japan 990512)",
    is_4rd_strike = false,
    ground_offset = 23,
    p1input = {x = 44, y = 34},
    p2input = {x = 310, y = 34},
    inputhistory = {x = 4, y = 49, step_y = 10},
    parry = true,
    highjump = true,
    fastwakeup = true,
    characters =
    {
      "gill",
      "alex",
      "ryu",
      "yun",
      "dudley",
      "necro",
      "hugo",
      "ibuki",
      "elena",
      "oro",
      "yang",
      "ken",
      "sean",
      "urien",
      "gouki",
      "gill",
      "chunli",
      "makoto",
      "q",
      "twelve",
      "remy",
    }
  },
  sfiii4n = {
    name = "Street Fighter III 3rd Strike - 4rd Arrange Edition 2013 (990608)",
    is_4rd_strike = true,
    ground_offset = 23,
    p1input = {x = 44, y = 34},
    p2input = {x = 310, y = 34},
    inputhistory = {x = 4, y = 49, step_y = 10},
    parry = true,
    highjump = true,
    fastwakeup = true,
    characters =
    {
      "gill",
      "alex",
      "ryu",
      "yun",
      "dudley",
      "necro",
      "hugo",
      "ibuki",
      "elena",
      "oro",
      "yang",
      "ken",
      "sean",
      "urien",
      "gouki",
      "usean",
      "chunli",
      "makoto",
      "q",
      "twelve",
      "remy",
    }
  },
  ssf2xjr1 = {
    name = "Super Street Fighter II X - Grand Master Challenge (Japan 940223)",
    is_4rd_strike = false,
    ground_offset = -15,
    p1input = {x = 32, y = 44},
    p2input = {x = 322, y = 44},
    inputhistory = {x = 4, y = 65, step_y = 9},
    parry = false,
    highjump = false,
    fastwakeup = false,
    characters =
    {
      "ryu",
      "ehonda",
      "blanka",
      "guile",
      "ken",
      "chunli",
      "zangief",
      "dhalsim",
      "dictator",
      "sagat",
      "boxer",
      "claw",
      "cammy",
      "thawk",
      "feilong",
      "deejay",
    }
  },
}
